#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          lnls
# Should-Start:      $network $syslog
# Should-Stop:       $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop lnls
# Description:       lnls is Linux Neighbour logging system
# log neighbour table entries
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Don't modify this line, change or create /etc/default/bind9.
OPTIONS=""
RESOLVCONF=no

test -f /etc/default/lnls && . /etc/default/lnls

. /lib/lsb/init-functions
PIDFILE=/var/run/lnls.pid

check_network() {
    if [ -z "$(/sbin/ifconfig $IFCONFIG_OPTS)" ]; then
       #log_action_msg "No networks configured."
       return 1
    fi
    return 0
}

case "$1" in
    start)
	log_daemon_msg "Starting linux neighbour logging system..." "lnls"

	# create pidfile with owner and group set to lnls.
	if [ -x $PIDFILE ]; then
	    log_action_msg "lnls already running - not starting"
	    log_end_msg 1
	else
	    touch $PIDFILE
	    chown lnls:lnls $PIDFILE
	fi

	if [ ! -x /usr/bin/lnls ]; then
	    log_action_msg "lnls binary missing - not starting"
	    log_end_msg 1
	fi

	if ! check_network; then
	    log_action_msg "no networks configured"
	    log_end_msg 1
	fi

	if start-stop-daemon --start --oknodo --quiet --exec /usr/bin/lnls \
		--daemon --syslog --pidfile ${PIDFILE} $OPTIONS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;

    stop)
	log_daemon_msg "Stopping linux neighbour logging system..." "lnls"
	if ! check_network; then
	    log_action_msg "no networks configured"
	    log_end_msg 1
	fi

	if [ -z $pid ]; then
	    pid=$(pgrep -f ^/usr/bin/lnls) || true
	    start-stop-daemon --stop --oknodo --quiet --exec /usr/bin/lnls \
		    --pidfile ${PIDFILE} -- $OPTIONS
	fi

	if [ -n $pid ]; then
	  while kill -0 $pid 2>/dev/null; do
	    log_progress_msg "waiting for pid $pid to die"
	    sleep 1
	  done
	fi
	log_end_msg 0
    ;;

    reload|force-reload)
	log_daemon_msg "Reloading linux neighbour loggin system..." "lnls"
	
	$0 restart
    ;;

    restart)
	if ! check_network; then
	    log_action_msg "no networks configured"
	    exit 1
	fi

	$0 stop
	$0 start
    ;;
    
    status)
    	ret=0
	status_of_proc -p ${PIDFILE} /usr/bin/lnls lnls 2>/dev/null || ret=$?
	exit $ret
	;;

    *)
	log_action_msg "Usage: /etc/init.d/lnls {start|stop|reload|restart|force-reload|status}"
	exit 1
    ;;
esac

exit 0
